services:
  web: # must agree with Rakefile
    image: whimsy-web
    build: .
    ports:
      - "1999:1999"
    environment:
      - "HOST_HOME=$HOME"
    volumes:
      - ..:/srv
    # Needed to run puppeteer
    cap_add:
      - SYS_ADMIN
    # Seems to be needed to run puppeteer on macOS with Apple chips
    platform: linux/amd64