version: '3'
services:
  web:
    image: whimsy-web
    build: .
    ports: 
      - "1999:80"
    environment:
      - "HOST_HOME=$HOME"
    volumes:
      - ../..:/srv
      - $HOME/.subversion:/root/.subversion
      - $HOME:/root
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.ssh:/root/.ssh
      - $HOME:$HOME
