name: dummy
# Try to see if can use 
on:
  push:

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, 'macos-latest']
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: setup agenda 1
      run: |
        set -v
        which -a ruby
        ruby --version
        sudo which -a ruby
        sudo ruby --version
        # try to run local version of ruby
        sudo $(dirname $(which ruby))/ruby --version
