name: test action

on:
  push:
    paths:
      - '**/testaction.yml'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: generate status
        run: |
          test ${{ matrix.os }} == 'macos-latest'
      - name: report
        if: always()
        run: |
          echo ${{ job.status }}