name: Unit test agenda
on:
  push:
    paths:
      - '**/unittestagenda.yml'
      - 'www/board/agenda/**'
      - 'lib/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, 'macos-latest']
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup
      run: |
        sudo apt-get install libldap2-dev
        sudo apt-get install libsasl2-dev
        sudo apt-get install nodejs
      if:  matrix.os != 'macos-latest'  
    - uses: actions/setup-node@v2
      with:
        node-version: '14'    
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: setup agenda 1
      run: |
        cd www/board/agenda
        npm install
        bundle install
    - name: install ldap for sudo
      # trying to sort out missing/incompatible ldap under sudo
      run: |
        sudo gem install ldap
    - name: setup agenda 2
      run: |
        sudo -E ruby -I $PWD/lib -I$(dirname $(gem which wunderbar)) -r whimsy/asf -e "ASF::LDAP.configure"
    - name: test agenda code
      run: |
        cd www/board/agenda
        # bundle exec rake
