name: Unit test agenda
on:
  push:
    paths:
      - '**/unittestagenda.yml'
      - 'www/board/agenda/**'
      - 'lib/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, 'macos-latest']
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup Ubuntu missing header files
      run: |
        sudo apt-get install libldap2-dev
        sudo apt-get install libsasl2-dev
      if:  matrix.os == 'ubuntu-20.04'  
    - uses: actions/setup-node@v2
      with:
        node-version: '14.19.1'
        # it seems that using the default Ubuntu version of node (14.19.0)
        # somehow fails to set the correct path for rake to use
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: setup agenda 1
      run: |
        cd www/board/agenda
        bundle install
    - name: setup agenda 2
      # need to run the ruby that has all the gems installed
      run: |
        sudo $(which ruby) -I $PWD/lib -r whimsy/asf -e "ASF::LDAP.configure"
    - name: Tweak chromedriver
      run: |
        which -a google-chrome || true
        google-chrome --version || true
        chromedriver --version || true
    - name: test agenda code
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        cd www/board/agenda
        bundle exec rake
