name: Unit test agenda
on:
  push:
    paths:
      - '**/unittestagenda.yml'
      - 'www/board/agenda/**'
      - 'lib/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup
      run: |
        sudo apt-get install libldap2-dev
        sudo apt-get install libsasl2-dev
      if:  ${{ matrix.os }} != 'macos-latest'  
    - uses: actions/setup-node@v2
      with:
        node-version: '14'    
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: test agenda code
      run: |
        cd www/board/agenda
        npm install
        bundle install
        bundle exec rake
