name: Unit test agenda
on:
  push:
    paths:
      - '**/unittestagenda.yml'
      - 'www/board/agenda/**'
      - 'lib/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-latest]
        ruby: [2.7, 3.1]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: test agenda code
      run: |
        cd www/board/agenda
        bundle install
        bundle exec rake
