name: Unit test navigation
# Separate job for debugging navigation issues
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup Ubuntu missing header files
      run: |
        sudo apt-get install libldap2-dev
        sudo apt-get install libsasl2-dev
      if:  matrix.os == 'ubuntu-20.04'  
    - uses: actions/setup-node@v2
      with:
        node-version: '14.19.1'
        # it seems that using the default Ubuntu version of node (14.19.0)
        # somehow fails to set the correct path for rake to use
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: test agenda navigation code
      run: |
        cd www/board/agenda
        TEST_AO_PAGE=1 bundle exec rspec spec/navigation_spec.rb
