name: Unit test agenda
on:
  push:
    paths:
      - '**/unittestagenda.yml'
      - 'www/board/agenda/**'
      - 'lib/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, 'macos-latest']
        ruby: [2.7.1]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup
      run: |
        sudo apt-get install libldap2-dev
        sudo apt-get install libsasl2-dev
        sudo apt-get install nodejs
      if:  matrix.os != 'macos-latest'  
    - uses: actions/setup-node@v2
      with:
        node-version: '14'    
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: setup agenda 1
      run: |
        cd www/board/agenda
        npm install
        bundle install
    - name: setup agenda 2
      # need to run the ruby that has all the gems installed
      run: |
        sudo $(dirname $(which ruby))/ruby -I $PWD/lib -r whimsy/asf -e "ASF::LDAP.configure"
        gem list
        ruby --version
        node --version
    - name: test agenda code
      run: |
        cd www/board/agenda
        npm list vue
        bundle exec rake
